# Curated list of major government crypto policies
STATIC_POLICIES = [
    {
        "id": 1,
        "date": "2021-09-07",
        "country": "El Salvador",
        "region": "Latin America",
        "title": "Bitcoin Becomes Legal Tender",
        "summary": "El Salvador became the first country to adopt Bitcoin as legal tender, requiring all businesses to accept BTC as payment.",
        "impact": "bullish",
        "category": "Legal Tender",
        "source_url": "https://www.bbc.com/news/business-58096484",
    },
    {
        "id": 2,
        "date": "2021-09-24",
        "country": "China",
        "region": "Asia",
        "title": "China Declares All Crypto Transactions Illegal",
        "summary": "China's central bank declared all cryptocurrency-related transactions illegal, intensifying its crackdown on crypto trading and mining.",
        "impact": "bearish",
        "category": "Ban",
        "source_url": "https://www.reuters.com/world/china/china-central-bank-vows-crackdown-cryptocurrency-trading-2021-09-24/",
    },
    {
        "id": 3,
        "date": "2022-03-09",
        "country": "United States",
        "region": "North America",
        "title": "Biden Executive Order on Crypto",
        "summary": "President Biden signed an executive order directing federal agencies to study digital assets, explore a U.S. CBDC, and develop a regulatory framework.",
        "impact": "neutral",
        "category": "Executive Order",
        "source_url": "https://www.whitehouse.gov/briefing-room/presidential-actions/2022/03/09/executive-order-on-ensuring-responsible-development-of-digital-assets/",
    },
    {
        "id": 4,
        "date": "2022-11-11",
        "country": "United States",
        "region": "North America",
        "title": "FTX Collapse & Congressional Response",
        "summary": "The collapse of FTX exchange triggered urgent calls in U.S. Congress for comprehensive crypto regulation legislation.",
        "impact": "bearish",
        "category": "Regulatory Response",
        "source_url": "https://www.cnbc.com/2022/11/11/ftx-files-for-bankruptcy.html",
    },
    {
        "id": 5,
        "date": "2023-06-05",
        "country": "United States",
        "region": "North America",
        "title": "SEC Sues Binance and Coinbase",
        "summary": "The SEC filed lawsuits against Binance and Coinbase, alleging they operated as unregistered securities exchanges.",
        "impact": "bearish",
        "category": "Enforcement",
        "source_url": "https://www.sec.gov/litigation/litreleases/2023/lr25740.htm",
    },
    {
        "id": 6,
        "date": "2023-06-09",
        "country": "European Union",
        "region": "Europe",
        "title": "MiCA Regulation Enacted",
        "summary": "The EU's Markets in Crypto-Assets (MiCA) regulation was formally enacted, creating the world's first comprehensive crypto regulatory framework.",
        "impact": "neutral",
        "category": "Regulation",
        "source_url": "https://www.esma.europa.eu/esmas-activities/digital-finance-and-innovation/markets-crypto-assets-regulation-mica",
    },
    {
        "id": 7,
        "date": "2024-01-10",
        "country": "United States",
        "region": "North America",
        "title": "SEC Approves Bitcoin Spot ETFs",
        "summary": "The SEC approved 11 spot Bitcoin ETFs, including products from BlackRock, Fidelity, and Invesco, opening crypto investment to traditional finance.",
        "impact": "bullish",
        "category": "ETF Approval",
        "source_url": "https://www.sec.gov/news/press-release/2024-6",
    },
    {
        "id": 8,
        "date": "2024-05-23",
        "country": "United States",
        "region": "North America",
        "title": "SEC Approves Ethereum Spot ETFs",
        "summary": "The SEC approved spot Ethereum ETF applications from VanEck, BlackRock, Fidelity, and others, further legitimizing crypto assets.",
        "impact": "bullish",
        "category": "ETF Approval",
        "source_url": "https://www.sec.gov/news/press-release/2024-68",
    },
    {
        "id": 9,
        "date": "2024-05-22",
        "country": "United States",
        "region": "North America",
        "title": "FIT21 Act Passes House",
        "summary": "The Financial Innovation and Technology for the 21st Century Act (FIT21) passed the U.S. House with bipartisan support, establishing a regulatory framework dividing oversight between SEC and CFTC.",
        "impact": "bullish",
        "category": "Legislation",
        "source_url": "https://financialservices.house.gov/news/documentsingle.aspx?DocumentID=409248",
    },
    {
        "id": 10,
        "date": "2024-07-25",
        "country": "United States",
        "region": "North America",
        "title": "SAB 121 Repeal Attempt",
        "summary": "Congress passed legislation to overturn SEC's SAB 121 guidance that restricted banks from holding crypto; Biden vetoed the measure.",
        "impact": "neutral",
        "category": "Legislation",
        "source_url": "https://www.congress.gov/bill/118th-congress/house-joint-resolution/109",
    },
    {
        "id": 11,
        "date": "2024-12-12",
        "country": "South Korea",
        "region": "Asia",
        "title": "South Korea Virtual Asset User Protection Act",
        "summary": "South Korea's Virtual Asset User Protection Act came into full effect, requiring crypto exchanges to safeguard user assets and imposing strict AML/KYC rules.",
        "impact": "neutral",
        "category": "Regulation",
        "source_url": "https://www.fsc.go.kr/",
    },
    {
        "id": 12,
        "date": "2025-01-23",
        "country": "United States",
        "region": "North America",
        "title": "Trump Executive Order: Digital Asset Stockpile",
        "summary": "President Trump signed an executive order directing the creation of a national digital asset stockpile and establishing a crypto advisory council.",
        "impact": "bullish",
        "category": "Executive Order",
        "source_url": "https://www.whitehouse.gov",
    },
    {
        "id": 13,
        "date": "2025-03-02",
        "country": "United States",
        "region": "North America",
        "title": "Trump Signs Bitcoin Strategic Reserve Order",
        "summary": "President Trump signed an executive order establishing a U.S. Strategic Bitcoin Reserve, directing the Treasury to hold Bitcoin as a national reserve asset.",
        "impact": "bullish",
        "category": "Strategic Reserve",
        "source_url": "https://www.whitehouse.gov",
    },
]


def get_all_policies(country: str = None, impact: str = None) -> list:
    policies = sorted(STATIC_POLICIES, key=lambda x: x["date"], reverse=True)
    if country:
        policies = [p for p in policies if country.lower() in p["country"].lower()]
    if impact:
        policies = [p for p in policies if p["impact"] == impact]
    return policies
